version: 2.1

orbs:
  go: circleci/go@1.10.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.21.4'
    steps:
      - checkout
      - run:
          name: linux AMD
          command: go build -o bogus .

workflows:
  circleci-logs-build:
    jobs:
      - build