version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go1.18.6
    steps:
      - checkout
      - run:
          name: linux AMD
          command: go build -o bogus .

workflows:
  circleci-logs-build:
    jobs:
      - build